// Package typesafe provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package typesafe

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Answer An answer whose type matches the corresponding question.
type Answer struct {
	union json.RawMessage
}

// ChoiceAnswer The selected choice, confidence, and probabilities for a choice question.
type ChoiceAnswer struct {
	// Choice The name of the choice with the highest probability among the question's criteria.
	//
	// Examples: angry
	Choice string `json:"choice"`

	// Confidence Confidence in the selected choice, from 0 to 1. Higher values indicate greater certainty; use lower values to flag uncertain selections for review.
	//
	// Examples: 0.9
	Confidence float64 `json:"confidence"`

	// Probabilities Probability of each choice in criteria, keyed by choice name, from 0 to 1. Shows how likely the alternatives are; values sum to approximately 1.
	//
	// Examples: {"angry":0.8,"calm":0.1,"excited":0.1}
	Probabilities map[string]float64 `json:"probabilities"`

	// Type Identifies a selection from the requested choices.
	//
	// Examples: choice
	Type string `json:"type"`
}

// ChoiceQuestion A question that selects one option from the choices you define.
type ChoiceQuestion struct {
	// Criteria Choice names and descriptions of when each applies. A choice without a description is interpreted by its name alone.
	//
	// Examples: {"angry":"An upset or hostile message","calm":"A neutral or polite message","excited":"An enthusiastic or eager message"}
	Criteria map[string]any `json:"criteria"`

	// Instructions What the model should decide when choosing an option.
	//
	// Examples: What is the tone of this message?
	Instructions any `json:"instructions,omitempty"`

	// Type Identifies a question that selects one of the choices in criteria.
	//
	// Examples: choice
	Type string `json:"type"`
}

// HTTPValidationError Request validation failures returned with HTTP status 422.
type HTTPValidationError struct {
	// Detail Validation errors describing which request values are missing or invalid.
	//
	// Examples: [{"loc":["body","state"],"msg":"Field required","type":"missing"}]
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// ModelMetadata A model or model alias available to the authenticated account.
type ModelMetadata struct {
	// Description Human-readable description of the model and its capabilities.
	//
	// Examples: General-purpose system one model.
	Description string `json:"description"`

	// Name Model name or alias accepted by the request's model field.
	//
	// Examples: jev-latest
	Name string `json:"name"`

	// ReleaseDate Model release date, formatted as YYYY-MM-DD.
	//
	// Examples: 2026-09-15
	ReleaseDate string `json:"release_date"`
}

// ModelMetadataList Models and aliases available to the authenticated account.
type ModelMetadataList struct {
	// Models Available models and aliases. Use a model's name in POST /v1/systemone requests.
	//
	// Examples: [{"description":"General-purpose system one model.","name":"jev-latest","release_date":"2026-09-15"}]
	Models []ModelMetadata `json:"models"`
}

// NoulAnswer The probability of a yes answer or a true statement.
type NoulAnswer struct {
	// Noul Probability of a yes answer or a true statement, from 0 to 1. Values near 1 favor yes or true, values near 0 favor no or false, and values near 0.5 indicate uncertainty.
	//
	// Examples: 0.98
	Noul float64 `json:"noul"`

	// Type Identifies a yes/no answer.
	//
	// Examples: noul
	Type string `json:"type"`
}

// NoulCriteria Criteria defining what counts as a yes or no answer.
type NoulCriteria struct {
	// False What counts as a no answer.
	//
	// Examples: The message is a legitimate conversation.
	False any `json:"false,omitempty"`

	// True What counts as a yes answer.
	//
	// Examples: The message is unsolicited advertising.
	True any `json:"true,omitempty"`
}

// NoulQuestion A yes/no question or statement, answered with the probability of yes or true.
type NoulQuestion struct {
	// Criteria Criteria clarifying what counts as a yes or no answer.
	//
	// Examples: {"false":"A legitimate conversation","true":"Unsolicited advertising"}
	Criteria *NoulCriteria `json:"criteria,omitempty"`

	// Instructions The yes/no question or statement to evaluate.
	//
	// Examples: Is this message spam?, This message contains unsolicited advertising., {"task":"Identify unsolicited advertising."}
	Instructions any `json:"instructions,omitempty"`

	// Type Identifies a yes/no question or statement.
	//
	// Examples: noul
	Type string `json:"type"`
}

// Question A question about the supplied content.
type Question struct {
	union json.RawMessage
}

// ScoreAnswer An expected score with its rubric, confidence, and score-level probabilities.
type ScoreAnswer struct {
	// Confidence Confidence in the score, from 0 to 1. Higher values indicate greater certainty; use lower values to flag uncertain ratings for review.
	//
	// Examples: 0.9
	Confidence float64 `json:"confidence"`

	// Legend The requested criteria mapped to their score levels, so you can interpret the score.
	//
	// Examples: {"0":"Can wait","1":"Needs attention this week","2":"Needs attention today"}
	Legend map[string]any `json:"legend"`

	// Probabilities Probability of each score level, from 0 to 1, using the same keys as legend. Shows how likely the alternatives are; values sum to approximately 1.
	//
	// Examples: {"0":0.1,"1":0.1,"2":0.8}
	Probabilities map[string]float64 `json:"probabilities"`

	// Score Expected score: the probability-weighted average of the rubric levels. May fall between integer levels.
	//
	// Examples: 1.7
	Score float64 `json:"score"`

	// Type Identifies a rating against the requested score levels.
	//
	// Examples: score
	Type string `json:"type"`
}

// ScoreQuestion A question that assigns a score using an ordered rubric.
type ScoreQuestion struct {
	// Criteria Ordered descriptions of the score levels. Each description's position determines its score, starting at zero.
	//
	// Examples: ["Can wait","Needs attention this week","Needs attention today"]
	Criteria []any `json:"criteria"`

	// Instructions What the model should rate.
	//
	// Examples: How urgent is this message?
	Instructions any `json:"instructions,omitempty"`

	// Type Identifies a question that rates the content using the levels in criteria.
	//
	// Examples: score
	Type string `json:"type"`
}

// SystemOneRequest Content and named questions to evaluate together using a TypeSafe model.
type SystemOneRequest struct {
	// Model Name or alias of the model to use. Available names are returned by GET /v1/models.
	//
	// Examples: jev-latest
	Model string `json:"model"`

	// Questions Questions to ask about the content, each with a name you choose. The response uses those names to identify the answers.
	//
	// Examples: {"billing":{"instructions":"Is this message about billing?","type":"noul"}}
	Questions map[string]Question `json:"questions"`

	// State The content all questions in this request refer to.
	//
	// Examples: I was charged twice. Please help., {"message":"Please help.","subject":"Duplicate charge"}
	State any `json:"state"`
}

// SystemOneResponse Answers grouped by question name, with the model used and token usage.
type SystemOneResponse struct {
	// Answers Answers keyed by the question names supplied in the request. Each answer's type matches its question's type.
	//
	// Examples: {"billing":{"noul":0.98,"type":"noul"}}
	Answers map[string]Answer `json:"answers"`

	// Model Name of the model that answered the questions. May differ from the alias supplied in the request.
	//
	// Examples: jev-latest
	Model string `json:"model"`

	// Usage Token usage for the request.
	Usage Usage `json:"usage"`
}

// Usage Token usage for the request.
type Usage struct {
	// InputTokens Number of billable input tokens used to evaluate the request.
	//
	// Examples: 120
	InputTokens int `json:"input_tokens"`

	// OutputTokens Number of output tokens used to answer the questions. Output tokens are currently free of charge.
	//
	// Examples: 12
	OutputTokens int `json:"output_tokens"`
}

// ValidationError A request validation error at a specific field or array element.
type ValidationError struct {
	// Ctx Additional context used to explain the validation failure.
	//
	// Examples: {"min_length":1}
	Ctx *map[string]interface{} `json:"ctx,omitempty"`

	// Input The input value that failed validation.
	//
	// Examples: {"type":"score"}
	Input interface{} `json:"input,omitempty"`

	// Loc Path to the invalid value: the request location followed by field names and array indices.
	//
	// Examples: ["body","questions","urgency","score","criteria"]
	Loc []ValidationError_Loc_Item `json:"loc"`

	// Msg Human-readable explanation of the validation failure.
	//
	// Examples: Field required
	Msg string `json:"msg"`

	// Type Machine-readable validation error code.
	//
	// Examples: missing
	Type string `json:"type"`
}

// ValidationErrorLoc0 defines model for ValidationError.Loc.0.
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for ValidationError.Loc.1.
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// SystemoneV1SystemonePostJSONRequestBody defines body for SystemoneV1SystemonePost for application/json ContentType.
type SystemoneV1SystemonePostJSONRequestBody = SystemOneRequest

// AsNoulAnswer returns the union data inside the Answer as a NoulAnswer
func (t Answer) AsNoulAnswer() (NoulAnswer, error) {
	var body NoulAnswer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulAnswer overwrites any union data inside the Answer as the provided NoulAnswer
func (t *Answer) FromNoulAnswer(v NoulAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	t.union = b
	return err
}

// MergeNoulAnswer performs a merge with any union data inside the Answer, using the provided NoulAnswer
func (t *Answer) MergeNoulAnswer(v NoulAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreAnswer returns the union data inside the Answer as a ScoreAnswer
func (t Answer) AsScoreAnswer() (ScoreAnswer, error) {
	var body ScoreAnswer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreAnswer overwrites any union data inside the Answer as the provided ScoreAnswer
func (t *Answer) FromScoreAnswer(v ScoreAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	t.union = b
	return err
}

// MergeScoreAnswer performs a merge with any union data inside the Answer, using the provided ScoreAnswer
func (t *Answer) MergeScoreAnswer(v ScoreAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceAnswer returns the union data inside the Answer as a ChoiceAnswer
func (t Answer) AsChoiceAnswer() (ChoiceAnswer, error) {
	var body ChoiceAnswer
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceAnswer overwrites any union data inside the Answer as the provided ChoiceAnswer
func (t *Answer) FromChoiceAnswer(v ChoiceAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	t.union = b
	return err
}

// MergeChoiceAnswer performs a merge with any union data inside the Answer, using the provided ChoiceAnswer
func (t *Answer) MergeChoiceAnswer(v ChoiceAnswer) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Answer) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Answer) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "choice":
		return t.AsChoiceAnswer()
	case "noul":
		return t.AsNoulAnswer()
	case "score":
		return t.AsScoreAnswer()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Answer) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Answer) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNoulQuestion returns the union data inside the Question as a NoulQuestion
func (t Question) AsNoulQuestion() (NoulQuestion, error) {
	var body NoulQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNoulQuestion overwrites any union data inside the Question as the provided NoulQuestion
func (t *Question) FromNoulQuestion(v NoulQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	t.union = b
	return err
}

// MergeNoulQuestion performs a merge with any union data inside the Question, using the provided NoulQuestion
func (t *Question) MergeNoulQuestion(v NoulQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"noul"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChoiceQuestion returns the union data inside the Question as a ChoiceQuestion
func (t Question) AsChoiceQuestion() (ChoiceQuestion, error) {
	var body ChoiceQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChoiceQuestion overwrites any union data inside the Question as the provided ChoiceQuestion
func (t *Question) FromChoiceQuestion(v ChoiceQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	t.union = b
	return err
}

// MergeChoiceQuestion performs a merge with any union data inside the Question, using the provided ChoiceQuestion
func (t *Question) MergeChoiceQuestion(v ChoiceQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"choice"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScoreQuestion returns the union data inside the Question as a ScoreQuestion
func (t Question) AsScoreQuestion() (ScoreQuestion, error) {
	var body ScoreQuestion
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScoreQuestion overwrites any union data inside the Question as the provided ScoreQuestion
func (t *Question) FromScoreQuestion(v ScoreQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	t.union = b
	return err
}

// MergeScoreQuestion performs a merge with any union data inside the Question, using the provided ScoreQuestion
func (t *Question) MergeScoreQuestion(v ScoreQuestion) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"score"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Question) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Question) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "choice":
		return t.AsChoiceQuestion()
	case "noul":
		return t.AsNoulQuestion()
	case "score":
		return t.AsScoreQuestion()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Question) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Question) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
